### ISSUE TITLE
Must generate word counts

### ISSUE THREAD

**Issue by izahn** [tedunderwood/DataMunging#1]
On the step 

```
I can just write clean text files (with suffix clean.txt)
or I can also write tab-separated files that count the words
in each file after correction.
1) Text only or 2) text-plus-wordcounts? (1 or 2): 1) Text only or 2) text-plus-wordcounts? (1 or 2): 1
```

the OCRnormalizer.py script only works if I select 2. If I select 1 I get

```
Traceback (most recent call last):
  File "OCRnormalizer.py", line 351, in <module>
    main()
  File "OCRnormalizer.py", line 313, in main
    metatuple = (outfilename, str(totalwordsinvol), str(pre_matched), str(pre_english), str(post_matched),
UnboundLocalError: local variable 'totalwordsinvol' referenced before assignment
```

**Comment by tedunderwood** [comment]
Thanks for the notification.

Ted

Ted Underwood
Professor of English
Liberal Arts and Sciences Centennial Scholar
University of Illinois, Urbana-Champaign
